---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-ib-service-intro"
      label: "Ib Service Intro"
      solveButton: false
    - name: "02-define-a-blueprint"
      label: "Define A Blueprint"
      solveButton: false
    - name: "03-viewing-your-image"
      label: "Viewing Your Image"
      solveButton: false
    - name: "04-guestfish"
      label: "Guestfish"
      solveButton: false
    - name: "05-virt-customize"
      label: "Virt Customize"
      solveButton: false
    - name: "06-guestfish-verify"
      label: "Guestfish Verify"
      solveButton: false

tabs:
  - name: ">_ terminal"
    url: /wetty
