`+virt-customize+` is another libguestfs interface tool that will let
you edit a disk image. `+guestfish+` is great for interactive editing
(and is of course able to be scripted), and `+virt-customize+` is better
for actions that are carried out automatically.

For instance. With `+guestfish+` I could either directly create, or
script the creation, of a file within a guest image. With
`+virt-customize+` it’s easier to just place an already created file, or
install that file via an rpm. These are both powerful tools, that serve
similar jobs in different ways.

Let’s add a welcome message to the image. We'll copy the motd file into the image. You can view the contents of the motd file with the following command.

[source,bash,run]
----
cat /root/motd
----

So we’ll use `+virt-copy-in+` to set the motd to the contents of that file.

[source,bash,run]
----
virt-copy-in -a /var/lib/libvirt/images/composer_api_disk.qcow2 /root/motd /etc
----

`+virt-copy-in+` will let us copy files in place and set permissions. Let’s say we’ve got a sudoers drop-in we’d like in place on
all of our systems. In your home directory is a drop-in to allow users in the `+superusers+` group to control the `+sshd+` service.

Then to be safe, we should correct the permissions on the file that we
just placed.

[source,bash,run]
----
virt-customize -a /var/lib/libvirt/images/composer_api_disk.qcow2 --chmod 0640:/etc/motd
----

Now, in the next step, we’ll use guestfish again to verify our changes.
