---
virtualmachines:
  - name: "rhel"
    image: "rhel-10-0-07-09-25-3"
    memory: "4G"
    bootloader: efi
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    cdroms:
      - metadata:
          name: "vm-image"
        spec:
          source:
            pvc:
              name: "imagebuilder-service-lab-08-21-25"
              namespace: cnv-images
          pvc:
            accessModes:
              - ReadWriteMany
            volumeMode: Block
            resources:
              requests:
                storage: "20Mi"
